# -*- coding: utf-8 -*-
"""eixo5_grupoa4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JlHjXgfB7onzmzqCD_FRtIueoiHuwQmI

# **1. Importação, carregamento e visão geral dos dados**
"""

import pandas as pd

df = pd.read_excel("cleaned_dataset_.xlsx")

display(df)

df.info()

df = df.drop(columns= ['Unnamed: 14', 'Unnamed: 15'])
df.info()

df.shape

df.describe()

df.isnull().sum()

df["order_date"].min(), df["order_date"].max()

"""Conhecendo as variáveis categóricas"""

df.product_category.value_counts(dropna=False)

df.customer_region.value_counts(dropna=False)

df.payment_method.value_counts(dropna=False)

"""Agregando as vendas por dia"""

sales_daily = df.groupby("order_date")["quantity_sold"].sum().reset_index()

"""Gráfico de sazonalidades"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

plt.plot(sales_daily["order_date"], sales_daily["quantity_sold"])

plt.title("Evolução das Vendas ao Longo do Tempo")
plt.xlabel("Data")
plt.ylabel("Quantidade Vendida")

plt.show()

"""Criando a variável mês"""

df["month"] = df["order_date"].dt.month

"""Agregando as vendas por mês"""

sales_by_month = df.groupby("month")["quantity_sold"].sum().reset_index()

"""Gráfico de sazonalidade por mês, mas atenção dessa forma tenho os dois anos juntos"""

plt.figure(figsize=(10,5))

bars = plt.bar(sales_by_month["month"], sales_by_month["quantity_sold"])

plt.title("Vendas por Mês")
plt.xlabel("Mês")
plt.ylabel("Quantidade Vendida")

# adicionando os valores nas barras
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        int(height),
        ha='center',
        va='bottom'
    )

plt.show()

"""Extraindo o ano da data"""

df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["day_of_week"] = df["order_date"].dt.dayofweek
df["day_of_year"] = df["order_date"].dt.dayofyear

"""Agregando as Vendas X Ano"""

sales_month_year = (
    df.groupby(["year", "month"])["quantity_sold"]
    .sum()
    .reset_index()
)

import seaborn as sns

plt.figure(figsize=(10,5))

sns.lineplot(
    data=sales_month_year,
    x="month",
    y="quantity_sold",
    hue="year",
    marker="o"
)

plt.title("Sazonalidade Mensal das Vendas por Ano")
plt.xlabel("Mês")
plt.ylabel("Quantidade Vendida")

plt.show()

"""Vendas X Categoria"""

sales_by_category = (
    df.groupby("product_category")["quantity_sold"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

plt.figure(figsize=(10,5))

ax = sns.barplot(
    data=sales_by_category,
    x="product_category",
    y="quantity_sold"
)

plt.title("Quantidade Vendida por Categoria")
plt.xlabel("Categoria")
plt.ylabel("Quantidade Vendida")

# adicionando os valores nas barras
for container in ax.containers:
    ax.bar_label(container)

plt.show()

"""Receita total x categoria"""

revenue_by_category = (
    df.groupby("product_category")["total_revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

plt.figure(figsize=(10,5))

ax = sns.barplot(
    data=revenue_by_category,
    x="product_category",
    y="total_revenue"
)

# adiciona os valores nas barras
ax.bar_label(ax.containers[0])

plt.title("Receita Total por Categoria")
plt.xlabel("Categoria")
plt.ylabel("Receita")

plt.show()

"""Variáveis Numéricas"""

df.hist(bins=50, figsize=(20,15))
plt.show()

"""# **2. Preparando os dados**

Transformando variáveis categóricas em variáveis numéricas
"""

df = pd.get_dummies(df, columns=["product_category"])

df = pd.get_dummies(df, columns=["payment_method"])

df = pd.get_dummies(df, columns=["customer_region"])

df.columns

display(df)

"""# **Data**"""

import numpy as np

df["order_date"] = pd.to_datetime(df["order_date"])

df = df.sort_values("order_date")

"""1. Extrair componentes básicos"""

df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["day"] = df["order_date"].dt.day
df["day_of_week"] = df["order_date"].dt.dayofweek

"""2. Criar variáveis mais inteligentes

Sazonalidade semanal
"""

df["is_weekend"] = df["day_of_week"].isin([5,6]).astype(int)

"""Início ou fim do mês"""

df["is_month_start"] = df["order_date"].dt.is_month_start.astype(int)
df["is_month_end"] = df["order_date"].dt.is_month_end.astype(int)

"""Trimestre"""

df["quarter"] = df["order_date"].dt.quarter

"""3. Encoding cíclico

Mês e dia da semana são variáveis cíclicas (dezembro → janeiro, domingo → segunda).
Se não tratarmos isso, o modelo entende errado.
"""

df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

df["dow_sin"] = np.sin(2 * np.pi * df["day_of_week"] / 7)
df["dow_cos"] = np.cos(2 * np.pi * df["day_of_week"] / 7)

"""4. Criar features de histórico"""

df["lag_1"] = df["quantity_sold"].shift(1)
df["lag_7"] = df["quantity_sold"].shift(7)

df["rolling_mean_7"] = df["quantity_sold"].rolling(7).mean()

df = df.dropna()

"""# **3. Separando as amostras**"""

split_date = "2023-01-01"

train = df[df["order_date"] < split_date]
test = df[df["order_date"] >= split_date]

X_train = train.drop(columns=["quantity_sold", "total_revenue", "profit", "order_date"])
y_train = train[["quantity_sold"]]

X_test = test.drop(columns=["quantity_sold", "total_revenue", "profit", "order_date"])
y_test = test[["quantity_sold"]]

"""### **Modelo com DecisionTreeRegressor para Previsão de `quantity_sold`**"""

from sklearn.tree import DecisionTreeRegressor, plot_tree

# Criar e treinar a Árvore de Decisão
model_dt = DecisionTreeRegressor(criterion='squared_error', max_depth=3)
model_dt.fit(X_train, y_train)

# Previsão e Acurácia (para regressão, podemos usar MAE ou R^2)
from sklearn.metrics import mean_absolute_error, r2_score
previsoes_dt = model_dt.predict(X_test)
print(f"MAE: {mean_absolute_error(y_test, previsoes_dt):.2f}")
print(f"R^2: {r2_score(y_test, previsoes_dt):.2f}")

# Visualizar a Árvore
plt.figure(figsize=(18,12))
plot_tree(model_dt, filled=True, feature_names=X_train.columns, rounded=True, fontsize=10)
plt.title("Árvore de Decisão para Previsão de Quantidade Vendida")
plt.show()

"""### **Modelo com RandomForestRegressor para Previsão de `quantity_sold`**"""

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

"""Fazendo a previsão com Random Forest Regressor"""

y_pred = model.predict(X_test)

"""Avaliando o Random Forest Regressor"""

print(mean_absolute_error(y_test, y_pred))

"""### **Modelo com XGBoost para Previsão de `quantity_sold`**"""

pip install xgboost

from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

"""Fazendo a previsão com XGBoost"""

y_pred_xgb = xgb_model.predict(X_test)

"""Avaliando o XGBoost"""

print(f"MAE do XGBoost: {mean_absolute_error(y_test, y_pred_xgb)}")

"""### **Comparação Visual das Previsões: Random Forest vs XGBoost**"""

plt.figure(figsize=(15, 7))

# Criando um DataFrame para facilitar a plotagem
# Selecionando uma amostra para melhor visualização
sample_size = 200

plot_df = pd.DataFrame({
    'Actual': y_test['quantity_sold'].values[:sample_size],
    'RandomForest_Pred': y_pred[:sample_size],
    'XGBoost_Pred': y_pred_xgb[:sample_size]
})

plt.plot(plot_df['Actual'], label='Valores Reais', alpha=0.7)
plt.plot(plot_df['RandomForest_Pred'], label='Previsão Random Forest', linestyle='--')
plt.plot(plot_df['XGBoost_Pred'], label='Previsão XGBoost', linestyle=':')

plt.title('Comparação de Previsões: Real vs. Random Forest vs. XGBoost (Amostra)')
plt.xlabel('Amostra de Observações no Conjunto de Teste')
plt.ylabel('Quantidade Vendida')
plt.legend()
plt.grid(True)
plt.show()